spring.application.name=20_MVC_Product

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://nozomi.proxy.rlwy.net:37950/railway
spring.datasource.username=root
spring.datasource.password=mttEtdVzVUdbwmERtKKmstgdIJlXSvnB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

admin.user.name=admin
admin.user.pass=admin@123

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
server.port=${PORT:8080}
